"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LineReader = exports.FReader = exports.FWriter = exports.FileC = void 0;
const filec_1 = require("./filec");
Object.defineProperty(exports, "FileC", { enumerable: true, get: function () { return filec_1.FileC; } });
const reader_1 = require("./reader");
Object.defineProperty(exports, "FReader", { enumerable: true, get: function () { return reader_1.FReader; } });
Object.defineProperty(exports, "LineReader", { enumerable: true, get: function () { return reader_1.LineReader; } });
const writer_1 = require("./writer");
Object.defineProperty(exports, "FWriter", { enumerable: true, get: function () { return writer_1.FWriter; } });
